### ISSUE TITLE
pool address question

### ISSUE THREAD

**Issue by cbarraford** [Commercionetwork/Cosmos-Hackathom-2019#6]
@RiccardoM I was at the hackathon as well and I was reading through your code to help learn more about he Cosmos SDK. I do have a question about your code if you don't mind.

https://github.com/Commercionetwork/Cosmos-Hackatom-2019/blob/master/x/pool/keeper.go#L35

Where does this "0000000000000" number come from? Why that string and not something else? Is that secure? What is stopping another module from stealing those funds in the pool?

**Comment by rmontagnin** [comment]
Hi @cbarraford, thanks for asking! 

> Where does this "0000000000000" number come from? Why that string and not something else? Is that secure?

Usually the 0 address is used as a burn address in every chain system. This is done because finding a mnemonic that links to it is pretty difficult and thus it can be considered safe to send funds to it.

However, the second part of your question is very smart. 

> What is stopping another module from stealing those funds in the pool?

Ideally, nothing. If one module knows that the funds are all stored inside the 0x0 wallet, it can retrieve funds from it without any problem. This could be fixed by storing the amount present inside the pool as a simple integer, and just use the `Subtract` method to burn money out of the investors' wallets.

**Comment by cbarraford** [comment]
@RiccardoM thanks for getting back to me. Ok, so 0x0 address is commonly a burner address for the reason you gave. But there has to be something I'm missing here because the security doesn't make sense to me. 

First you subtract coins from an actual person's wallet without any kind of authentication beyond the rest/cli endpoints. Just seems that if i have a person's `sdk.AccAddress` (which I assume is public information?) that means I can build a module that can take whatever I want from it?
Then you put the coins into a 0x0 address, only to remove them later, again, without any private key needed/etc. You mentioned storing an int and using the `Subtract` method, but in a malicious module that someone else builds, they can just steal everything?

**Comment by rmontagnin** [comment]
@cbarraford What you point out is completely correct. You are perfectly right when asking the following: 

> Just seems that if i have a person's sdk.AccAddress (which I assume is public information?) that means I can build a module that can take whatever I want from it?

The short answer is: yes. 

Actually, the "steal" thing would work only on the validators that are running your full node executable and this that are validating blocks on your chain. You can't create a module that steals from other chains, as the executables will be different and so the chains themselves. 

When we build every module into our Cosmos application, we create a full node executable that allows to sign and send transactions as we define them. After that, the executable will perform actions writing on the database representing our blockchain (that's what the keeper does). If we decide that with a particular transaction we can steal everything and we hard code it into our executable, then we will able to do so. But this is our choice as developers. 

In this case the security does't matter when looking just as the keeper. The address validation is performed before going into the keeper. If the signer of the transaction is not the one controlling the address he wrote inside the transaction itself, then the validation will fail and we won't execute the code inside the keeper. That is preventing us from unwanted movements between the users wallets. 

Just remember that each Cosmos application is a separate chain that cannot write directly the database of another chain (another Cosmos application). That's what preventing other people from creating modules that can steal from our application. In short, each application is self-contained.

**Comment by cbarraford** [comment]
@RiccardoM thanks so much for taking the time to answer my silly questions. Much appreciated. 👍

**Comment by rmontagnin** [comment]
@cbarraford Don't worry, no question is silly :wink: Thanks for raising the problem of the 0x0 address!
